services:
  db:
    image: "${IMAGE}"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "0269306032DbB"
      POSTGRES_DB: "routing"
    ports:
      - "5432:5432"
    volumes:
      - postgis/postgis:15-3.4-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - appdata:/app
      - ./wait-for.sh:/app/wait-for.sh
      - ./app.env:/app/app.env
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}?sslmode=disable
    entrypoint: [ "/app/wait-for.sh", "db:5432", "--timeout=400", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

volumes:
  pgdata:
  appdata:

